### ISSUE TITLE
Get recently viewed variants

### ISSUE THREAD

**Issue by JayBox325** [mattgrayisok/craft-recently-viewed#1]
I have used your plugin on a project, but the way we're using variants is that the product is a range and the variants are the specific products within that range as it seems to suit our client's product hierarchy better.

But this means I'm trying to use the following tag:

```
{% set recentVariants = craft.variants.recentlyViewed().orderByDateViewed().all() %}
```

And my template throws the following:

```
array_reverse() expects parameter 1 to be array, null given

    public function beforePrepare(): bool
    {
        if($this->recentlyViewed) {
            $recentIds = Craft::$app->getSession()->get('rv-recent-ids');
            $this->owner->subQuery->andWhere(['elements.id' => $recentIds]);
            if ($this->orderByDateViewed) {
                $recentIds = Craft::$app->getSession()->get('rv-recent-ids');
                $this->owner->subQuery->orderBy([new \yii\db\Expression(
                'FIELD (elements.id, ' . implode(',', array_reverse($recentIds)) . ')' ⬅️
                )]);
                $this->owner->query->orderBy([new \yii\db\Expression(
                'FIELD (elements.id, ' . implode(',', array_reverse($recentIds)) . ')'
                )]);
            }
        }
        return true;
    }
}
```

⬅️ was the highlighted line in the template where an error was occurring.

Thanks!

**Comment by mattgrayisok** [comment]
@JayBox325 

Thanks for this! It's a null state error, unrelated to variants specifically. I'll push an update now

**Comment by mattgrayisok** [comment]
Fix added in v1.0.2. Thanks for testing!

**Comment by JayBox325** [comment]
Lovely stuff, glad to have helped. Thanks for the fix so soon. 👍🏼

**Comment by JayBox325** [comment]
Hi @mattgrayisok, 

I'm just coming back to this because I've finally gotten around to testing it and my returned array of recently viewed variants is still 0. Below is my markup, same as the initial post:

```
{% set recentVariants = craft.variants.recentlyViewed().orderByDateViewed().all() %}
```

This is returning `0`. Any advice on best way to debug this issue? I've clicked around a lot of different types of variants but nothing is changing. Cheers

**Comment by mattgrayisok** [comment]
Hi @JayBox325 

The auto tracking feature will only work with elements that Craft is able to natively associate with URLs. For instance you can do this with products using this bit in the Commerce product settings:

![image](https://user-images.githubusercontent.com/571107/50980186-0334a880-14f0-11e9-8cdb-95c3db3d33fd.png)

Unfortunately there's no equivalent setting for variants so they can't be linked natively to specific URLs.

Even though auto-tracking won't work we can still manually track them by adding the following to the template which is displaying the variant:

`{% do craft.recentlyViewed.track(variant) %}`

Where `variant` is the variable that references the current variant.

Just make sure that this isn't placed inside a `{% cache %}` block.

Once you've added that line to the template it should start working as expected.

Unfortunately there's no easy way to debug the internal state of the plugin from twig templates but I'll open a new issue to add a helper function for doing just that.

**Comment by JayBox325** [comment]
This works absolutely perfectly now. Top man. I'll send you a link to where it's used when it's live 👍🏼
