### ISSUE TITLE
Craft 4 compatibility

### ISSUE THREAD

**Issue by AndrewMac** [mattgrayisok/craft-recently-viewed#6]
Hi there, just wondering if you could confirm whether you have any plans to update this for Craft 4?
Thanks in advance, Andrew

**Comment by mattgrayisok** [comment]
Hey!

I'd forgotten about it! But the plugin should still work fine with Craft 4 so I'll get the composer.json updated and give it a quick test this week 👍

**Comment by mattgrayisok** [comment]
@AndrewMac v2.0.0 has just been released which adds Craft 4 support. 

No notable changes, just made everything compatible and ran a few tests.

**Comment by AndrewMac** [comment]
Thanks so much!
